app:
  api:
    users-path: /api/v1/users
    events-path: /api/v1/events
spring:
  application:
    name: asl-service
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:austin_scotch_lovers_db
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
